In [3]:
from os import listdir, makedirs
from os.path import isfile, join, exists
import pandas as pd
import numpy as np

data_base_path = 'prepared_data/stations'

In [8]:
for csv_file in listdir(data_base_path):
    print(pd.read_csv(join(data_base_path, csv_file)))

                         datetime   CO   NO2       SO2    O3  PM10   WS  \
0       2001-01-10 00:00:00+07:00  0.0  38.0  1.000000   5.0  46.0  0.4
1       2001-01-10 01:00:00+07:00  0.4  29.0  0.000000   3.0  56.0  0.3
2       2001-01-10 02:00:00+07:00  0.2  27.0  0.000000   4.0  34.0  0.4
3       2001-01-10 03:00:00+07:00  0.0  23.0  0.000000   8.0  24.0  0.4
4       2001-01-10 04:00:00+07:00  0.0  23.0  0.000000   8.0  24.0  0.4
...                           ...  ...   ...       ...   ...   ...  ...
271147  2031-12-16 19:00:00+07:00  1.9  53.0  4.000000  10.0  96.0  0.6
271148  2031-12-16 20:00:00+07:00  2.0  51.0  5.000000   6.0  98.0  0.7
271149  2031-12-16 21:00:00+07:00  2.1  50.0  6.000000   4.0  99.0  0.7
271150  2031-12-16 22:00:00+07:00  1.9  46.0  6.380952   4.0  92.0  0.7
271151  2031-12-16 23:00:00+07:00  1.9  43.0  5.000000   5.0  78.0  0.6

           WD  Temp   Rel hum  PM25
0       209.0  28.8      82.0  29.0
1       201.0  28.2      88.0  29.0
2       207.0  28.1      88.0  29.0
3       208.0  27.9      87.0  29.0
4       208.0  27.9      87.0  29.0
...       ...   ...       ...   ...
271147   29.0  30.8      47.0  25.0
271148   36.0  30.6      48.0  25.0
271149   37.0  30.8      49.0  25.0
271150   37.0  30.6      49.0  25.0
271151   36.0  30.3      50.0  25.0

[271152 rows x 11 columns]
                        datetime   CO   NO2   WS     WD  Temp  PM10  PM25  \
0      2017-03-22 00:00:00+07:00  0.4  21.0  2.5  195.0  31.7  43.0   NaN
1      2017-03-22 01:00:00+07:00  0.3  23.0  1.4  206.0  31.6  34.0   NaN
2      2017-03-22 02:00:00+07:00  0.3  26.0  0.9  187.0  30.9  27.0   NaN
3      2017-03-22 03:00:00+07:00  0.3  24.0  0.8  183.0  30.5  31.0   NaN
4      2017-03-22 04:00:00+07:00  0.4  26.0  1.0  187.0  30.6  27.0   NaN
...                          ...  ...   ...  ...    ...   ...   ...   ...
42614  2022-01-30 14:00:00+07:00  NaN   NaN  NaN    NaN   NaN  74.0  32.0
42615  2022-01-30 15:00:00+07:00  NaN   NaN  NaN    NaN   NaN  74.0  32.0
42616  2022-01-30 16:00:00+07:00  NaN   NaN  NaN    NaN   NaN  73.0  31.0
42617  2022-01-30 17:00:00+07:00  NaN   NaN  NaN    NaN   NaN  73.0  31.0
42618  2022-01-30 18:00:00+07:00  NaN   NaN  NaN    NaN   NaN  76.0  30.0

       SO2  O3
0      NaN NaN
1      NaN NaN
2      NaN NaN
3      NaN NaN
4      NaN NaN
...    ...  ..
42614  NaN NaN
42615  NaN NaN
42616  NaN NaN
42617  NaN NaN
42618  NaN NaN

[42619 rows x 10 columns]
                     datetime_aq  PM25  PM10  NO2  SO2  CO  O3
0      2020-07-20 19:00:00+07:00  22.0   NaN  NaN  NaN NaN NaN
1      2020-07-20 20:00:00+07:00  22.0   NaN  NaN  NaN NaN NaN
2      2020-07-20 21:00:00+07:00  22.0   NaN  NaN  NaN NaN NaN
3      2020-07-20 22:00:00+07:00  23.0   NaN  NaN  NaN NaN NaN
4      2020-07-20 23:00:00+07:00  23.0   NaN  NaN  NaN NaN NaN
...                          ...   ...   ...  ...  ...  ..  ..
13410  2022-01-30 13:00:00+07:00  30.0   NaN  NaN  NaN NaN NaN
13411  2022-01-30 14:00:00+07:00  30.0   NaN  NaN  NaN NaN NaN
13412  2022-01-30 15:00:00+07:00  29.0   NaN  NaN  NaN NaN NaN
13413  2022-01-30 16:00:00+07:00  29.0   NaN  NaN  NaN NaN NaN
13414  2022-01-30 17:00:00+07:00  29.0   NaN  NaN  NaN NaN NaN

[13415 rows x 7 columns]
                     datetime_aq  PM25  PM10  NO2  SO2  CO  O3
0      2020-07-20 19:00:00+07:00  11.0   NaN  NaN  NaN NaN NaN
1      2020-07-20 20:00:00+07:00  11.0   NaN  NaN  NaN NaN NaN
2      2020-07-20 21:00:00+07:00  11.0   NaN  NaN  NaN NaN NaN
3      2020-07-20 22:00:00+07:00  12.0   NaN  NaN  NaN NaN NaN
4      2020-07-20 23:00:00+07:00  12.0   NaN  NaN  NaN NaN NaN
...                          ...   ...   ...  ...  ...  ..  ..
13410  2022-01-30 13:00:00+07:00  20.0   NaN  NaN  NaN NaN NaN
13411  2022-01-30 14:00:00+07:00  20.0   NaN  NaN  NaN NaN NaN
13412  2022-01-30 15:00:00+07:00  20.0   NaN  NaN  NaN NaN NaN
13413  2022-01-30 16:00:00+07:00  19.0   NaN  NaN  NaN NaN NaN
13414  2022-01-30 17:00:00+07:00  20.0   NaN  NaN  NaN NaN NaN

[13415 rows x 7 columns]
                     datetime_aq  PM25  PM10  NO2  SO2  CO    O3
0      2020-07-20 19:00:00+07:00   NaN   NaN  NaN  NaN NaN  25.0
1      2020-07-20 20:00:00+07:00   NaN   NaN  NaN  NaN NaN  25.0
2      2020-07-20 21:00:00+07:00   NaN   NaN  NaN  NaN NaN  25.0
3      2020-07-20 22:00:00+07:00   NaN   NaN  NaN  NaN NaN  25.0
4      2020-07-20 23:00:00+07:00   NaN   NaN  NaN  NaN NaN  25.0
...                          ...   ...   ...  ...  ...  ..   ...
13410  2022-01-30 13:00:00+07:00   NaN   NaN  NaN  NaN NaN  25.0
13411  2022-01-30 14:00:00+07:00   NaN   NaN  NaN  NaN NaN  25.0
13412  2022-01-30 15:00:00+07:00   NaN   NaN  NaN  NaN NaN  25.0
13413  2022-01-30 16:00:00+07:00   NaN   NaN  NaN  NaN NaN  25.0
13414  2022-01-30 17:00:00+07:00   NaN   NaN  NaN  NaN NaN  25.0

[13415 rows x 7 columns]
                     datetime_aq  PM25  PM10  NO2  SO2  CO  O3
0      2020-07-20 19:00:00+07:00  28.0  56.0  NaN  NaN NaN NaN
1      2020-07-20 20:00:00+07:00  29.0  56.0  NaN  NaN NaN NaN
2      2020-07-20 21:00:00+07:00  28.0  56.0  NaN  NaN NaN NaN
3      2020-07-20 22:00:00+07:00  28.0  56.0  NaN  NaN NaN NaN
4      2020-07-20 23:00:00+07:00  28.0  55.0  NaN  NaN NaN NaN
...                          ...   ...   ...  ...  ...  ..  ..
13410  2022-01-30 13:00:00+07:00  35.0  51.0  NaN  NaN NaN NaN
13411  2022-01-30 14:00:00+07:00  35.0  51.0  NaN  NaN NaN NaN
13412  2022-01-30 15:00:00+07:00  34.0  51.0  NaN  NaN NaN NaN
13413  2022-01-30 16:00:00+07:00  33.0  50.0  NaN  NaN NaN NaN
13414  2022-01-30 17:00:00+07:00  33.0  49.0  NaN  NaN NaN NaN

[13415 rows x 7 columns]
                        datetime    CO  NO2  SO2    O3  PM10   WS     WD  \
0      2013-01-19 00:00:00+07:00  0.50  2.0  0.0  42.0  66.0  0.6   58.0
1      2013-01-19 01:00:00+07:00  0.30  4.0  0.0  31.0  68.0  0.8   51.0
2      2013-01-19 02:00:00+07:00  0.40  5.0  0.0  27.0  58.0  0.7   74.0
3      2013-01-19 03:00:00+07:00  0.30  2.0  0.0  34.0  60.0  0.9   75.0
4      2013-01-19 04:00:00+07:00  0.30  3.0  0.0  22.0  57.0  0.4  109.0
...                          ...   ...  ...  ...   ...   ...  ...    ...
79158  2022-01-30 06:00:00+07:00  0.60  NaN  4.0  10.0  38.0  NaN    NaN
79159  2022-01-30 07:00:00+07:00  0.62  NaN  4.0   9.0  38.0  NaN    NaN
79160  2022-01-30 08:00:00+07:00  0.63  NaN  4.0   8.0  38.0  NaN    NaN
79161  2022-01-30 09:00:00+07:00  0.64  NaN  4.0   6.0  38.0  NaN    NaN
79162  2022-01-30 10:00:00+07:00  0.64  NaN  4.0   5.0  38.0  NaN    NaN

       Temp   Rel hum  PM25
0      24.2      94.0   NaN
1      25.7      78.0   NaN
2      25.2      81.0   NaN
3      25.1      81.0   NaN
4      24.0      87.0   NaN
...     ...       ...   ...
79158   NaN       NaN  20.0
79159   NaN       NaN  20.0
79160   NaN       NaN  20.0
79161   NaN       NaN  20.0
79162   NaN       NaN  20.0

[79163 rows x 11 columns]
                        datetime    CO  NO2  SO2    O3  PM10   WS   WD  Temp  \
0      2010-02-08 00:00:00+07:00  0.75  1.0  2.0  18.0  36.0  0.0  0.0  18.1
1      2010-02-08 01:00:00+07:00  0.75  1.0  2.0  18.0  36.0  0.0  0.0  18.1
2      2010-02-08 02:00:00+07:00  0.75  1.0  2.0  18.0  36.0  0.0  0.0  18.1
3      2010-02-08 03:00:00+07:00  0.75  1.0  2.0  18.0  36.0  0.0  0.0  18.1
4      2010-02-08 04:00:00+07:00  0.75  1.0  2.0  18.0  36.0  0.0  0.0  18.1
...                          ...   ...  ...  ...   ...   ...  ...  ...   ...
73866  2022-01-30 13:00:00+07:00   NaN  NaN  2.0  16.0  33.0  NaN  NaN   NaN
73867  2022-01-30 14:00:00+07:00   NaN  NaN  2.0  21.0  33.0  NaN  NaN   NaN
73868  2022-01-30 15:00:00+07:00   NaN  NaN  2.0  27.0  33.0  NaN  NaN   NaN
73869  2022-01-30 16:00:00+07:00   NaN  NaN  2.0  32.0  34.0  NaN  NaN   NaN
73870  2022-01-30 17:00:00+07:00   NaN  NaN  2.0  37.0  34.0  NaN  NaN   NaN

        Rel hum  Rain  PM25
0          86.0   0.0   NaN
1          86.0   0.0   NaN
2          86.0   0.0   NaN
3          86.0   0.0   NaN
4          86.0   0.0   NaN
...         ...   ...   ...
73866       NaN   NaN  17.0
73867       NaN   NaN  17.0
73868       NaN   NaN  18.0
73869       NaN   NaN  18.0
73870       NaN   NaN  18.0

[73871 rows x 12 columns]
                        datetime  PM10  PM25    CO   NO2  SO2    O3   WS  \
0      2019-06-25 00:00:00+07:00  16.0   5.0  0.70   8.0  0.0   5.0  1.6
1      2019-06-25 01:00:00+07:00  11.0   5.0  0.70  11.0  1.0  12.0  1.3
2      2019-06-25 02:00:00+07:00  12.0   6.0  0.70   9.0  0.0  12.0  1.3
3      2019-06-25 03:00:00+07:00  12.0   7.0  0.70  10.0  0.0   9.0  1.0
4      2019-06-25 04:00:00+07:00  14.0   8.0  0.70  10.0  0.0   8.0  1.4
...                          ...   ...   ...   ...   ...  ...   ...  ...
22814  2022-01-30 14:00:00+07:00  38.0  22.0  0.60   4.0  2.0  29.0  NaN
22815  2022-01-30 15:00:00+07:00  38.0  22.0  0.55   3.0  1.0  35.0  NaN
22816  2022-01-30 16:00:00+07:00  38.0  22.0  0.50   4.0  1.0  41.0  NaN
22817  2022-01-30 17:00:00+07:00  38.0  22.0  0.50   4.0  1.0  41.0  NaN
22818  2022-01-30 18:00:00+07:00  38.0  22.0  0.47   8.0  1.0  46.0  NaN

          WD  Temp  Rain
0      197.0  26.6  93.0
1      151.0  25.9  95.0
2      187.0  26.3  94.0
3      257.0  26.3  95.0
4      243.0  26.2  95.0
...      ...   ...   ...
22814    NaN   NaN   NaN
22815    NaN   NaN   NaN
22816    NaN   NaN   NaN
22817    NaN   NaN   NaN
22818    NaN   NaN   NaN

[22819 rows x 11 columns]
                     datetime_aq  PM25  PM10  NO2  SO2    CO    O3
0      2020-10-10 14:00:00+07:00   6.0  15.0  NaN  1.0  0.87   5.0
1      2020-10-10 15:00:00+07:00   6.0  15.0  NaN  1.0  0.87   6.0
2      2020-10-10 16:00:00+07:00   7.0  15.0  NaN  1.0  0.87   6.0
3      2020-10-10 17:00:00+07:00   7.0  15.0  NaN  1.0  0.87   6.0
4      2020-10-10 18:00:00+07:00   7.0  15.0  NaN  1.0  0.87   6.0
...                          ...   ...   ...  ...  ...   ...   ...
11448  2022-01-30 14:00:00+07:00  43.0  56.0  NaN  2.5  1.04  29.0
11449  2022-01-30 15:00:00+07:00  43.0  56.0  NaN  2.5  0.98  32.0
11450  2022-01-30 16:00:00+07:00  43.0  56.0  NaN  2.5  0.90  35.0
11451  2022-01-30 17:00:00+07:00  43.0  56.0  NaN  2.5  0.90  35.0
11452  2022-01-30 18:00:00+07:00  43.0  56.0  NaN  2.5  0.83  38.0

[11453 rows x 7 columns]
                     datetime_aq  PM25  PM10  NO2  SO2  CO  O3
0      2020-07-20 19:00:00+07:00   6.0   NaN  NaN  NaN NaN NaN
1      2020-07-20 20:00:00+07:00   6.0   NaN  NaN  NaN NaN NaN
2      2020-07-20 21:00:00+07:00   6.0   NaN  NaN  NaN NaN NaN
3      2020-07-20 22:00:00+07:00   7.0   NaN  NaN  NaN NaN NaN
4      2020-07-20 23:00:00+07:00   7.0   NaN  NaN  NaN NaN NaN
...                          ...   ...   ...  ...  ...  ..  ..
13410  2022-01-30 13:00:00+07:00  50.0   NaN  NaN  NaN NaN NaN
13411  2022-01-30 14:00:00+07:00  49.0   NaN  NaN  NaN NaN NaN
13412  2022-01-30 15:00:00+07:00  49.0   NaN  NaN  NaN NaN NaN
13413  2022-01-30 16:00:00+07:00  48.0   NaN  NaN  NaN NaN NaN
13414  2022-01-30 17:00:00+07:00  48.0   NaN  NaN  NaN NaN NaN

[13415 rows x 7 columns]
                        datetime  PM10  PM25   WS     WD  Temp  Rain  NO2  \
0      2019-12-01 00:00:00+07:00  12.0   3.0  0.7   37.0  21.9  97.0  NaN
1      2019-12-01 01:00:00+07:00  16.0   4.0  0.4   89.0  22.7  96.0  NaN
2      2019-12-01 02:00:00+07:00  13.0   4.0  0.4  116.0  22.6  96.0  NaN
3      2019-12-01 03:00:00+07:00  16.0   3.0  0.3   69.0  22.5  96.0  NaN
4      2019-12-01 04:00:00+07:00  13.0   3.0  0.5  103.0  22.5  96.0  NaN
...                          ...   ...   ...  ...    ...   ...   ...  ...
18998  2022-01-30 14:00:00+07:00  39.0  18.5  NaN    NaN   NaN   NaN  NaN
18999  2022-01-30 15:00:00+07:00  39.0  18.5  NaN    NaN   NaN   NaN  NaN
19000  2022-01-30 16:00:00+07:00  39.0  18.5  NaN    NaN   NaN   NaN  NaN
19001  2022-01-30 17:00:00+07:00  39.0  18.5  NaN    NaN   NaN   NaN  NaN
19002  2022-01-30 18:00:00+07:00  38.0  18.5  NaN    NaN   NaN   NaN  NaN

       SO2  CO  O3
0      NaN NaN NaN
1      NaN NaN NaN
2      NaN NaN NaN
3      NaN NaN NaN
4      NaN NaN NaN
...    ...  ..  ..
18998  NaN NaN NaN
18999  NaN NaN NaN
19000  NaN NaN NaN
19001  NaN NaN NaN
19002  NaN NaN NaN

[19003 rows x 11 columns]
                     datetime_aq  PM25  PM10  NO2  SO2  CO  O3
0      2020-07-20 19:00:00+07:00  21.0  34.0  NaN  NaN NaN NaN
1      2020-07-20 20:00:00+07:00  21.0  35.0  NaN  NaN NaN NaN
2      2020-07-20 21:00:00+07:00  21.0  35.0  NaN  NaN NaN NaN
3      2020-07-20 22:00:00+07:00  21.0  34.0  NaN  NaN NaN NaN
4      2020-07-20 23:00:00+07:00  21.0  34.0  NaN  NaN NaN NaN
...                          ...   ...   ...  ...  ...  ..  ..
13410  2022-01-30 13:00:00+07:00  24.0  35.0  NaN  NaN NaN NaN
13411  2022-01-30 14:00:00+07:00  23.0  36.0  NaN  NaN NaN NaN
13412  2022-01-30 15:00:00+07:00  23.0  34.0  NaN  NaN NaN NaN
13413  2022-01-30 16:00:00+07:00  22.0  35.0  NaN  NaN NaN NaN
13414  2022-01-30 17:00:00+07:00  22.0  34.0  NaN  NaN NaN NaN

[13415 rows x 7 columns]
                        datetime    CO   O3  PM10   WS    WD   Rel hum  Temp  \
0      2010-01-01 00:00:00+07:00  0.90  2.1  38.0  0.3  14.0      82.0  16.3
1      2010-01-01 01:00:00+07:00  0.80  1.9  54.0  0.3  27.0      86.0  15.8
2      2010-01-01 02:00:00+07:00  0.70  1.6  60.0  0.2  74.0      87.0  15.2
3      2010-01-01 03:00:00+07:00  0.60  3.5  45.0  0.4  73.0      87.0  14.8
4      2010-01-01 04:00:00+07:00  0.60  3.1  32.0  0.4  11.0      88.0  14.4
...                          ...   ...  ...   ...  ...   ...       ...   ...
65995  2022-01-30 14:00:00+07:00  0.43  4.0  32.0  NaN   NaN       NaN   NaN
65996  2022-01-30 15:00:00+07:00  0.42  4.0  32.0  NaN   NaN       NaN   NaN
65997  2022-01-30 16:00:00+07:00  0.40  4.0  33.0  NaN   NaN       NaN   NaN
65998  2022-01-30 17:00:00+07:00  0.40  4.0  33.0  NaN   NaN       NaN   NaN
65999  2022-01-30 18:00:00+07:00  0.35  4.0  33.0  NaN   NaN       NaN   NaN

       PM25  NO2  SO2
0       NaN  NaN  NaN
1       NaN  NaN  NaN
2       NaN  NaN  NaN
3       NaN  NaN  NaN
4       NaN  NaN  NaN
...     ...  ...  ...
65995  24.0  0.0  NaN
65996  24.0  0.0  NaN
65997  24.0  0.0  NaN
65998  24.0  0.0  NaN
65999  25.0  0.0  NaN

[66000 rows x 11 columns]
                     datetime_aq  PM25  PM10  NO2  SO2  CO  O3
0      2020-07-20 19:00:00+07:00   9.0  22.0  NaN  NaN NaN NaN
1      2020-07-20 20:00:00+07:00   9.0  23.0  NaN  NaN NaN NaN
2      2020-07-20 21:00:00+07:00  10.0  24.0  NaN  NaN NaN NaN
3      2020-07-20 22:00:00+07:00  10.0  26.0  NaN  NaN NaN NaN
4      2020-07-20 23:00:00+07:00  11.0  28.0  NaN  NaN NaN NaN
...                          ...   ...   ...  ...  ...  ..  ..
13410  2022-01-30 13:00:00+07:00  22.0  41.0  NaN  NaN NaN NaN
13411  2022-01-30 14:00:00+07:00  21.0  40.0  NaN  NaN NaN NaN
13412  2022-01-30 15:00:00+07:00  21.0  39.0  NaN  NaN NaN NaN
13413  2022-01-30 16:00:00+07:00  20.0  38.0  NaN  NaN NaN NaN
13414  2022-01-30 17:00:00+07:00  20.0  37.0  NaN  NaN NaN NaN

[13415 rows x 7 columns]
                     datetime_aq  PM25  PM10  NO2  SO2  CO  O3
0      2020-07-20 19:00:00+07:00  19.0   NaN  NaN  NaN NaN NaN
1      2020-07-20 20:00:00+07:00  19.0   NaN  NaN  NaN NaN NaN
2      2020-07-20 21:00:00+07:00  19.0   NaN  NaN  NaN NaN NaN
3      2020-07-20 22:00:00+07:00  20.0   NaN  NaN  NaN NaN NaN
4      2020-07-20 23:00:00+07:00  20.0   NaN  NaN  NaN NaN NaN
...                          ...   ...   ...  ...  ...  ..  ..
13410  2022-01-30 13:00:00+07:00  34.0   NaN  NaN  NaN NaN NaN
13411  2022-01-30 14:00:00+07:00  33.0   NaN  NaN  NaN NaN NaN
13412  2022-01-30 15:00:00+07:00  33.0   NaN  NaN  NaN NaN NaN
13413  2022-01-30 16:00:00+07:00  33.0   NaN  NaN  NaN NaN NaN
13414  2022-01-30 17:00:00+07:00  32.0   NaN  NaN  NaN NaN NaN

[13415 rows x 7 columns]
                     datetime_aq  PM25  PM10  NO2  SO2  CO  O3
0      2020-07-20 19:00:00+07:00   9.0   NaN  NaN  NaN NaN NaN
1      2020-07-20 20:00:00+07:00   9.0   NaN  NaN  NaN NaN NaN
2      2020-07-20 21:00:00+07:00   8.0   NaN  NaN  NaN NaN NaN
3      2020-07-20 22:00:00+07:00   8.0   NaN  NaN  NaN NaN NaN
4      2020-07-20 23:00:00+07:00   9.0   NaN  NaN  NaN NaN NaN
...                          ...   ...   ...  ...  ...  ..  ..
13410  2022-01-30 13:00:00+07:00  35.5   NaN  NaN  NaN NaN NaN
13411  2022-01-30 14:00:00+07:00  35.5   NaN  NaN  NaN NaN NaN
13412  2022-01-30 15:00:00+07:00  35.0   NaN  NaN  NaN NaN NaN
13413  2022-01-30 16:00:00+07:00  34.0   NaN  NaN  NaN NaN NaN
13414  2022-01-30 17:00:00+07:00  34.0   NaN  NaN  NaN NaN NaN

[13415 rows x 7 columns]
                     datetime_aq  PM25  PM10  NO2  SO2  CO  O3
0      2020-07-20 19:00:00+07:00  24.0   NaN  NaN  NaN NaN NaN
1      2020-07-20 20:00:00+07:00  24.0   NaN  NaN  NaN NaN NaN
2      2020-07-20 21:00:00+07:00  25.0   NaN  NaN  NaN NaN NaN
3      2020-07-20 22:00:00+07:00  25.0   NaN  NaN  NaN NaN NaN
4      2020-07-20 23:00:00+07:00  25.0   NaN  NaN  NaN NaN NaN
...                          ...   ...   ...  ...  ...  ..  ..
13410  2022-01-30 13:00:00+07:00  32.0   NaN  NaN  NaN NaN NaN
13411  2022-01-30 14:00:00+07:00  32.0   NaN  NaN  NaN NaN NaN
13412  2022-01-30 15:00:00+07:00  32.0   NaN  NaN  NaN NaN NaN
13413  2022-01-30 16:00:00+07:00  31.0   NaN  NaN  NaN NaN NaN
13414  2022-01-30 17:00:00+07:00  30.0   NaN  NaN  NaN NaN NaN

[13415 rows x 7 columns]
                        datetime    CO    O3  NO2  SO2  PM10   Rel hum   WS  \
0      2010-01-01 00:00:00+07:00  0.50  33.0  6.0  0.0  27.0      88.2  1.6
1      2010-01-01 01:00:00+07:00  0.50  30.0  5.0  0.0  40.0      90.0  1.3
2      2010-01-01 02:00:00+07:00  0.40  29.0  4.0  0.0  20.0      90.6  1.5
3      2010-01-01 03:00:00+07:00  0.50  31.0  4.0  0.0  17.0      89.9  1.2
4      2010-01-01 04:00:00+07:00  0.60  27.0  4.0  0.0  28.0      91.4  1.6
...                          ...   ...   ...  ...  ...   ...       ...  ...
74547  2022-01-30 13:00:00+07:00  0.46  14.0  NaN  7.0  45.0       NaN  NaN
74548  2022-01-30 14:00:00+07:00  0.46  14.0  NaN  7.0  45.0       NaN  NaN
74549  2022-01-30 15:00:00+07:00  0.46  27.0  NaN  5.0  45.0       NaN  NaN
74550  2022-01-30 16:00:00+07:00  0.46  35.0  NaN  7.0  45.0       NaN  NaN
74551  2022-01-30 17:00:00+07:00  0.46  40.0  NaN  6.0  45.0       NaN  NaN

          WD  Temp  PM25
0      180.0  26.4   NaN
1      196.0  26.8   NaN
2      193.0  26.6   NaN
3      191.0  26.7   NaN
4      189.0  26.4   NaN
...      ...   ...   ...
74547    NaN   NaN  24.0
74548    NaN   NaN  24.0
74549    NaN   NaN  24.0
74550    NaN   NaN  24.0
74551    NaN   NaN  24.0

[74552 rows x 11 columns]
                        datetime   CO    O3  NO2  SO2  PM10  PM25
0      1995-06-15 00:00:00+07:00  0.0  10.0  0.0  3.0  50.0   NaN
1      1995-06-15 01:00:00+07:00  0.2   5.0  1.0  4.0  26.0   NaN
2      1995-06-15 02:00:00+07:00  0.1   5.0  0.0  4.0  28.0   NaN
3      1995-06-15 03:00:00+07:00  0.0   4.0  0.0  4.0  25.0   NaN
4      1995-06-15 04:00:00+07:00  0.0   4.0  0.0  4.0  22.0   NaN
...                          ...  ...   ...  ...  ...   ...   ...
53275  2022-01-30 14:00:00+07:00  NaN  37.0  1.0  1.0  40.0  23.0
53276  2022-01-30 15:00:00+07:00  NaN  44.0  1.0  1.0  41.0  24.0
53277  2022-01-30 16:00:00+07:00  NaN  53.0  1.0  0.0  41.0  24.0
53278  2022-01-30 17:00:00+07:00  NaN  53.0  1.0  0.0  41.0  24.0
53279  2022-01-30 18:00:00+07:00  NaN  60.0  2.0  0.0  42.0  25.0

[53280 rows x 7 columns]
                        datetime    CO  PM10   WS     WD  Temp   Rel hum  \
0      2010-01-01 00:00:00+07:00  0.10  45.0  1.2   54.0  25.8      86.0
1      2010-01-01 01:00:00+07:00  0.30  50.0  0.6  178.0  22.9      89.0
2      2010-01-01 02:00:00+07:00  0.30  41.0  0.5  172.0  22.1      91.0
3      2010-01-01 03:00:00+07:00  0.25  30.0  0.3  175.0  22.2      90.0
4      2010-01-01 04:00:00+07:00  0.20  28.0  0.5  172.0  21.9      91.0
...                          ...   ...   ...  ...    ...   ...       ...
74778  2022-01-30 14:00:00+07:00   NaN  37.0  NaN    NaN   NaN       NaN
74779  2022-01-30 15:00:00+07:00   NaN  38.0  NaN    NaN   NaN       NaN

KeyboardInterrupt: